2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034428-v2a99l9i/logs/debug.log
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034428-v2a99l9i/logs/debug-internal.log
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 256, 'epochs': 10, 'hidden_size': 32, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:28,064 INFO    Thread-7 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:28,064 ERROR   Thread-7 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:28,068 INFO    Thread-7 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:38,089 INFO    Thread-8 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034438-mmiyq43q/logs/debug.log
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034438-mmiyq43q/logs/debug-internal.log
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 15, 'hidden_size': 256, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:38,090 INFO    Thread-8 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:38,090 ERROR   Thread-8 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:38,094 INFO    Thread-8 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034439-edklxtow/logs/debug.log
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034439-edklxtow/logs/debug-internal.log
2025-03-09 03:44:39,022 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:39,023 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_size': 256, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:39,023 INFO    Thread-9 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:39,023 ERROR   Thread-9 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:39,027 INFO    Thread-9 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:49,048 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034449-qfq4nw6b/logs/debug.log
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034449-qfq4nw6b/logs/debug-internal.log
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 15, 'hidden_size': 256, 'learning_rate': 0.001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:44:49,049 INFO    Thread-10 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:49,049 ERROR   Thread-10 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:49,053 INFO    Thread-10 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034450-vydjyd1f/logs/debug.log
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034450-vydjyd1f/logs/debug-internal.log
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:44:50,162 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 5, 'hidden_size': 32, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 3, 'optimizer': 'nadam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-09 03:44:50,163 INFO    Thread-11 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:44:50,163 ERROR   Thread-11 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:44:50,167 INFO    Thread-11 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034500-obquwryv/logs/debug.log
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034500-obquwryv/logs/debug-internal.log
2025-03-09 03:45:00,189 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:45:00,190 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 32, 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-09 03:45:00,190 INFO    Thread-12 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:45:00,190 ERROR   Thread-12 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:45:00,194 INFO    Thread-12 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Configure stats pid to 3619015
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/.config/wandb/settings
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from /speech/akshaya/zDA6401/as111/try1sweepX/wandb/settings
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034501-jeisgfqs/logs/debug.log
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/akshaya/zDA6401/as111/try1sweepX/wandb/run-20250309_034501-jeisgfqs/logs/debug-internal.log
2025-03-09 03:45:01,061 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:init():761] calling init triggers
2025-03-09 03:45:01,062 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_size': 64, 'learning_rate': 0.0001, 'loss': 'cross_entropy', 'num_layers': 5, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-09 03:45:01,062 INFO    Thread-13 (_run_job):3619015 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-09 03:45:01,062 ERROR   Thread-13 (_run_job):3619015 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-09 03:45:01,066 INFO    Thread-13 (_run_job):3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
2025-03-09 03:45:01,080 INFO    MainThread:3619015 [wandb_run.py:_finish():2112] finishing run ns24z274-iitm-ac-in/ns24z274_da6401_assignment1/d480lmis
