Traceback (most recent call last):
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 165, in __getattr__
    return self.__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 130, in __getitem__
    return self._items[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'weight_decay'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/speech/akshaya/zDA6401/for_confusion/train.py", line 21, in wandb_sweep
    weight_decay = config.weight_decay
                   ^^^^^^^^^^^^^^^^^^^
  File "/speech/akshaya/anaconda3/envs/dl1/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 167, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'weight_decay'
